const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT = 500;
const USER_ALREADY_EXIST = 409;
const UNATHORIZED = 401;
const FORBIDDEN = 403

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  USER_ALREADY_EXIST,
  UNATHORIZED,
  FORBIDDEN,
}